server {
    listen 8104;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /echowatt/ {
        try_files $uri $uri/ /echowatt/index.html;
    }

    # Redirect root / to /echowatt/
    location = / {
        return 301 /echowatt/;
    }
}
